// Generated from the AIU source workbook + corrected datatype migration. Single source of truth for table/column metadata.
export type ColumnType = "TEXT" | "BIGINT" | "DATE" | "TIMESTAMPTZ" | "JSONB";
export type TableName = "user_details" | "user_account_information" | "user_address_details" | "user_personal_details" | "client_details";
export interface ColumnMeta { column: string; source: string; type: ColumnType; pk?: boolean; fk?: string }
export interface TableMeta { name: TableName; label: string; pk: string | null; columns: ColumnMeta[] }
export const TABLES: TableMeta[] = [
  { name: "user_details", label: "User Details", pk: "client_code", columns: [
    {"column": "user_id", "source": "user ID", "type": "TEXT"},
    {"column": "client_code", "source": "Client Code", "type": "TEXT", "pk": true},
    {"column": "user_account_status_flag", "source": "User Account Status Flag", "type": "TEXT"},
    {"column": "user_update_date", "source": "User update date", "type": "TIMESTAMPTZ"},
    {"column": "user_equity_allowed", "source": "User Equity Allowed", "type": "TEXT"},
    {"column": "user_mf_allowed", "source": "User MF Allowed", "type": "TEXT"},
    {"column": "user_fno_allowed", "source": "User FNO Allowed", "type": "TEXT"},
    {"column": "user_commodity_allowed", "source": "User Commodity Allowed", "type": "TEXT"},
    {"column": "user_ipo_allowed", "source": "User IPO Allowed", "type": "TEXT"},
    {"column": "user_loan_allowed", "source": "User Loan Allowed", "type": "TEXT"},
    {"column": "user_first_active_date", "source": "User first Active date", "type": "TIMESTAMPTZ"},
    { "column": "data", "source": "(original source record)", "type": "JSONB" },
  ] },
  { name: "user_account_information", label: "User Account Information", pk: "form_number", columns: [
    {"column": "form_number", "source": "Form Number", "type": "BIGINT", "pk": true},
    {"column": "user_type_residential_nri", "source": "User Type(Residential, NRI)", "type": "TEXT"},
    {"column": "user_bank_account_number", "source": "User bank account number", "type": "TEXT"},
    {"column": "user_bank_customer_id", "source": "User bank customer id", "type": "TEXT"},
    {"column": "user_bank_brnch_code", "source": "User bank brnch code", "type": "TEXT"},
    {"column": "user_bank_account_type_self_joint", "source": "User bank account type(Self, Joint)", "type": "TEXT"},
    {"column": "user_bank_account_open_date", "source": "User bank account open date", "type": "TIMESTAMPTZ"},
    {"column": "client_code", "source": "Client Code", "type": "TEXT", "fk": "user_details.client_code"},
    {"column": "user_demat_account_open_date", "source": "User demat account open date", "type": "TIMESTAMPTZ"},
    {"column": "user_info_entered_by", "source": "User info entered by", "type": "TEXT"},
    {"column": "user_info_modified_by", "source": "User info modified by", "type": "TEXT"},
    {"column": "user_info_modified_date", "source": "User info modified date", "type": "TIMESTAMPTZ"},
    {"column": "user_bank_account_flag", "source": "user bank account flag", "type": "TEXT"},
    {"column": "user_bank_type", "source": "User bank type", "type": "TEXT"},
    { "column": "data", "source": "(original source record)", "type": "JSONB" },
  ] },
  { name: "user_address_details", label: "User Address Details", pk: null, columns: [
    {"column": "form_number", "source": "Form Number", "type": "BIGINT", "fk": "user_account_information.form_number"},
    {"column": "address_type_correspondance_permanent", "source": "Address type (Correspondance , Permanent)", "type": "TEXT"},
    {"column": "address_1", "source": "Address 1", "type": "TEXT"},
    {"column": "address_2", "source": "Address 2", "type": "TEXT"},
    {"column": "user_city", "source": "User City", "type": "TEXT"},
    {"column": "user_state", "source": "User state", "type": "TEXT"},
    {"column": "user_country", "source": "User Country", "type": "TEXT"},
    {"column": "user_pin", "source": "User Pin", "type": "TEXT"},
    {"column": "user_telephone_number", "source": "User telephone Number", "type": "TEXT"},
    {"column": "user_office_number", "source": "User Office Number", "type": "TEXT"},
    {"column": "user_mobile_number", "source": "User Mobile Number", "type": "TEXT"},
    {"column": "user_mail_address_flag", "source": "User Mail Address Flag", "type": "TEXT"},
    {"column": "user_details_entered_by", "source": "User Details Entered by", "type": "TEXT"},
    {"column": "user_details_entry_date", "source": "User details entry date", "type": "DATE"},
    {"column": "user_details_modified_by", "source": "User details modified by", "type": "TEXT"},
    {"column": "user_details_modified_date", "source": "User details modified date", "type": "DATE"},
    {"column": "user_address_same_as_correspondance", "source": "user address same as  correspondance", "type": "TEXT"},
    {"column": "user_ip", "source": "User IP", "type": "TEXT"},
    {"column": "user_mobile_relation", "source": "User Mobile Relation", "type": "TEXT"},
    {"column": "user_rm_preferred_location_pin", "source": "User RM  preferred location pin", "type": "TEXT"},
    { "column": "data", "source": "(original source record)", "type": "JSONB" },
  ] },
  { name: "user_personal_details", label: "User Personal Details", pk: null, columns: [
    {"column": "form_number", "source": "Form Number", "type": "BIGINT", "fk": "user_account_information.form_number"},
    {"column": "user_type_applicant_permanent", "source": "User Type(Applicant, Permanent)", "type": "TEXT"},
    {"column": "user_first_name", "source": "User First name", "type": "TEXT"},
    {"column": "user_middle_name", "source": "User Middle Name", "type": "TEXT"},
    {"column": "user_last_name", "source": "User last name", "type": "TEXT"},
    {"column": "user_dob", "source": "User DOB", "type": "DATE"},
    {"column": "user_sex", "source": "User Sex", "type": "TEXT"},
    {"column": "user_minor_flag", "source": "User Minor Flag", "type": "TEXT"},
    {"column": "user_email", "source": "User Email", "type": "TEXT"},
    {"column": "user_country_birth", "source": "User Country Birth", "type": "TEXT"},
    {"column": "user_nationality", "source": "User Nationality", "type": "TEXT"},
    {"column": "user_entered_employee_number", "source": "User Entered Employee Number", "type": "TEXT"},
    {"column": "user_details_entered_date", "source": "User Details entered date", "type": "TIMESTAMPTZ"},
    {"column": "user_details_modified_employee_number", "source": "User Details modified employee number", "type": "TEXT"},
    {"column": "userd_details_modified_date", "source": "Userd details modified date", "type": "TIMESTAMPTZ"},
    {"column": "user_designation", "source": "User designation", "type": "TEXT"},
    {"column": "user_relation", "source": "User relation", "type": "TEXT"},
    {"column": "user_user_id", "source": "User user id", "type": "TEXT"},
    {"column": "user_income_category", "source": "User Income Category", "type": "TEXT"},
    {"column": "user_marital_status", "source": "User Marital Status", "type": "TEXT"},
    {"column": "user_political_connect", "source": "User political Connect", "type": "TEXT"},
    {"column": "user_inperson_verification_date", "source": "User Inperson verification date", "type": "DATE"},
    {"column": "user_customer_type", "source": "User customer type", "type": "TEXT"},
    {"column": "user_update_ip", "source": "User update IP", "type": "TEXT"},
    {"column": "user_update_channel", "source": "User update channel", "type": "TEXT"},
    {"column": "user_us_person", "source": "User US Person", "type": "TEXT"},
    {"column": "user_tax_filing_country", "source": "User tax filing country", "type": "TEXT"},
    {"column": "user_place_of_birth", "source": "User place of birth", "type": "TEXT"},
    {"column": "user_email_relation", "source": "User email relation", "type": "TEXT"},
    {"column": "user_aadhar_last_4_digit", "source": "User Aadhar last 4 digit", "type": "TEXT"},
    {"column": "user_name_as_per_aadhar", "source": "User name as per aadhar", "type": "TEXT"},
    {"column": "user_aadhar_status", "source": "user aadhar status", "type": "TEXT"},
    {"column": "user_aadhar_consent_flag", "source": "user aadhar consent flag", "type": "TEXT"},
    { "column": "data", "source": "(original source record)", "type": "JSONB" },
  ] },
  { name: "client_details", label: "Client Details", pk: null, columns: [
    {"column": "form_number", "source": "Form Number", "type": "BIGINT", "fk": "user_account_information.form_number"},
    {"column": "customer_type_individual_huf", "source": "customer type(Individual, HUF)", "type": "TEXT"},
    {"column": "client_inward_date", "source": "Client inward date", "type": "DATE"},
    {"column": "client_scheme_type", "source": "client scheme type", "type": "TEXT"},
    {"column": "client_inward_status", "source": "client inward status", "type": "TEXT"},
    {"column": "client_inward_accept_date", "source": "client inward accept date", "type": "DATE"},
    {"column": "client_agreement_date", "source": "client agreement date", "type": "DATE"},
    {"column": "client_agent_code", "source": "client agent code", "type": "TEXT"},
    {"column": "client_sub_agent_code", "source": "client sub agent code", "type": "TEXT"},
    {"column": "client_product_type", "source": "client product type", "type": "TEXT"},
    {"column": "client_icici_emp_number", "source": "client icici emp number", "type": "TEXT"},
    {"column": "client_receipt_date", "source": "client receipt date", "type": "DATE"},
    {"column": "client_form_version", "source": "client form version", "type": "TEXT"},
    {"column": "client_user_id", "source": "client user id", "type": "TEXT"},
    {"column": "client_web_user_id", "source": "client web user id", "type": "TEXT"},
    {"column": "client_marital_status", "source": "client marital status", "type": "TEXT"},
    {"column": "client_education_code", "source": "client education code", "type": "TEXT"},
    {"column": "client_income_category_code", "source": "client income category code", "type": "TEXT"},
    {"column": "client_holding_range_code", "source": "client holding range code", "type": "TEXT"},
    {"column": "client_customer_nri_flag", "source": "client customer nri flag", "type": "TEXT"},
    {"column": "client_form_60_flag", "source": "client form 60 flag", "type": "TEXT"},
    {"column": "client_tax_assesse_flag", "source": "client tax assesse flag", "type": "TEXT"},
    {"column": "client_verification_date", "source": "client verification date", "type": "DATE"},
    {"column": "client_verify_status", "source": "client verify status", "type": "TEXT"},
    {"column": "client_ack_flag", "source": "client ack flag", "type": "TEXT"},
    {"column": "client_ack_date", "source": "client ack date", "type": "DATE"},
    {"column": "client_send_mail_flag", "source": "client send mail flag", "type": "TEXT"},
    {"column": "client_eba_upload_flag", "source": "client eba upload flag", "type": "TEXT"},
    {"column": "client_eba_upload_date", "source": "client eba upload date", "type": "DATE"},
    {"column": "client_last_flag", "source": "client last flag", "type": "TEXT"},
    {"column": "client_code", "source": "client code", "type": "TEXT", "fk": "user_details.client_code"},
    {"column": "client_rejection_mail_remarks", "source": "client rejection mail remarks", "type": "TEXT"},
    {"column": "client_details_entered_by", "source": "client details entered by", "type": "TEXT"},
    {"column": "client_details_entry_date", "source": "client details entry date", "type": "DATE"},
    {"column": "client_details_modified_by", "source": "client details modified by", "type": "TEXT"},
    {"column": "client_details_modified_date", "source": "client details modified date", "type": "DATE"},
    {"column": "client_pan_number", "source": "client pan number", "type": "TEXT"},
    {"column": "client_category_employee_code", "source": "client category employee code", "type": "TEXT"},
    {"column": "client_rm_code", "source": "client rm code", "type": "TEXT"},
    {"column": "client_nri_category_type", "source": "client nri category type", "type": "TEXT"},
    {"column": "client_nri_base_scheme", "source": "client nri base scheme", "type": "TEXT"},
    {"column": "client_nri_current_scheme", "source": "client nri current scheme", "type": "TEXT"},
    {"column": "client_non_isec_agent_code", "source": "client non isec agent code", "type": "TEXT"},
    {"column": "client_customer_type_change_date", "source": "client customer type change date", "type": "DATE"},
    {"column": "client_bank_type", "source": "client bank type", "type": "TEXT"},
    {"column": "client_settlement_type", "source": "client settlement type", "type": "TEXT"},
    {"column": "client_demat_mandate_category", "source": "client demat mandate category", "type": "TEXT"},
    {"column": "client_brokerage_model_flag", "source": "client brokerage model flag", "type": "TEXT"},
    { "column": "data", "source": "(original source record)", "type": "JSONB" },
  ] },
];
export const TABLE_BY_NAME = Object.fromEntries(TABLES.map((t) => [t.name, t])) as Record<TableName, TableMeta>;
