/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as RetrievalRouteImport } from './routes/retrieval'
import { Route as SchemaRouteImport } from './routes/schema'
import { Route as ValidationRouteImport } from './routes/validation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrievalRoute = RetrievalRouteImport.update({
  id: '/retrieval',
  path: '/retrieval',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaRoute = SchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/history': typeof HistoryRoute
  '/retrieval': typeof RetrievalRoute
  '/schema': typeof SchemaRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/history': typeof HistoryRoute
  '/retrieval': typeof RetrievalRoute
  '/schema': typeof SchemaRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/history': typeof HistoryRoute
  '/retrieval': typeof RetrievalRoute
  '/schema': typeof SchemaRoute
  '/validation': typeof ValidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/explorer' | '/history' | '/retrieval' | '/schema' | '/validation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explorer' | '/history' | '/retrieval' | '/schema' | '/validation'
  id:
    | '__root__'
    | '/'
    | '/explorer'
    | '/history'
    | '/retrieval'
    | '/schema'
    | '/validation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplorerRoute: typeof ExplorerRoute
  HistoryRoute: typeof HistoryRoute
  RetrievalRoute: typeof RetrievalRoute
  SchemaRoute: typeof SchemaRoute
  ValidationRoute: typeof ValidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrieval': {
      id: '/retrieval'
      path: '/retrieval'
      fullPath: '/retrieval'
      preLoaderRoute: typeof RetrievalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema': {
      id: '/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof SchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplorerRoute: ExplorerRoute,
  HistoryRoute: HistoryRoute,
  RetrievalRoute: RetrievalRoute,
  SchemaRoute: SchemaRoute,
  ValidationRoute: ValidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
